role_actions:
  - setup
  - update
  - get_logs
  - backup
  - restore
  - stop

gerrit_port: 8000

gerrit_pub_url: "https://example.com/r/"
gerrit_internal_url: "http://localhost:{{ gerrit_port }}/r/"

managesf_internal_url: "http://localhost:20001"

gerrit_email: "gerrit@example.com"

# Define service and admin user ssh keys to manage them
gerrit_service_rsa: ""
gerrit_service_rsa_pub: ""
gerrit_admin_rsa: ""
gerrit_admin_rsa_pub: ""

gerrit_email_pk: "CHANGE_ME"
gerrit_token_pk: "CHANGE_ME"

gitweb_cgi: "/var/www/git/gitweb.cgi"

gerrit_mysql_db: "gerrit"
gerrit_mysql_host: "mysql.example.com"
gerrit_mysql_password: "CHANGE_ME"
gerrit_mysql_port: 3306
gerrit_mysql_user: "gerrit"

gerrit_heap_limit: "512m"
gerrit_connection_pool: 225
