description: "All in one instance architecture"
inventory:
  - name: managesf
    ip: 192.168.135.101
    roles:
      - install-server
      - mysql
      - gateway
      - cauth
      - managesf
      - etherpad
      - lodgeit
      - gerrit
      - gerritbot
      - zuul
      - nodepool
      - jenkins
      - murmur
      - storyboard
      - storyboard-webclient
      - kibana
    mem: 8
    cpu: 4
    disk: 20
  - name: elk
    ip: 192.168.135.102
    roles:
      - elasticsearch
      - job-logs-gearman-client
      - job-logs-gearman-worker
      - logstash
