description: "Minimal 3 nodes sample deployment"
inventory:
  - name: managesf
    ip: 192.168.135.101
    roles:
      - install-server
      - mysql
      - cauth
      - gateway
      - managesf
      - statsd
    mem: 8
    cpu: 4
    disk: 20
  - name: jenkins
    ip: 192.168.135.102
    roles:
      - zuul
      - nodepool
      - jenkins
  - name: review
    ip: 192.168.135.103
    roles:
      - gerrit
