description: "All in one instance architecture"
inventory:
  - name: managesf
    ip: 192.168.135.101
    roles:
      - install-server
      - mysql
      - rabbitmq
      - gateway
      - cauth
      - managesf
      - etherpad
      - lodgeit
      - gerrit
      - gerritbot
      - zuul
      - nodepool
      - jenkins
      - murmur
      - elasticsearch
      - job-logs-gearman-client
      - job-logs-gearman-worker
      - logstash
      - kibana
      - mirror
      - storyboard
      - storyboard-webclient
      - mosquitto
      - germqtt
      - repoxplorer
    mem: 8
    cpu: 4
    disk: 20
