description: "One instances per service sample 10 nodes deployment"
inventory:
  - name: mysql
    roles:
      - install-server
      - mysql
  - name: managesf
    roles:
      - cauth
      - gateway
      - managesf
  - name: zuul
    roles:
      - zuul
  - name: nodepool
    roles:
      - nodepool
  - name: jenkins
    cpu: 4
    ram: 8
    roles:
      - jenkins
  - name: statsd
    roles:
      - statsd
  - name: murmur
    roles:
      - murmur
  - name: gerritbot
    roles:
      - gerritbot
  - name: review
    cpu: 4
    ram: 8
    roles:
      - gerrit
