description: "Multi jenkins master sample deployment"
inventory:
  - name: node01
    ip: 192.168.135.101
    roles:
      - install-server
      - mysql
      - cauth
      - gateway
      - managesf
      - statsd
      - zuul
      - nodepool
      - gerrit
  - name: jenkins01
    ip: 192.168.135.102
    roles:
      - jenkins
  - name: jenkins02
    ip: 192.168.135.103
    roles:
      - jenkins
