---
- name: "Backup data"
  synchronize:
    mode: pull
    src: "{{ item }}"
    dest: "{{ backup_dest }}/"
    delete: yes
    rsync_opts: --relative
  with_items:
    - /var/lib/gerrit/git
    - /etc/gerrit/replication.config
    - /etc/gerrit/ssh_host_rsa_key.pub
    - /etc/gerrit/ssh_host_rsa_key
    - /var/lib/gerrit/.ssh
    - /etc/httpd/managesf_htpasswd
