---

- include: sf_setup.yml

- hosts: managesf
  tasks:
    - name: Install upgrade-config-repo.sh
      template:
        src: "templates/upgrade-config-repo.sh.j2"
        dest: "/usr/local/bin/upgrade-config-repo.sh"
        mode: 0555

    - name: Copy default JJB definitions in /usr/local/share/sf-config-repo/
      template: src=templates/_default_jobs.yaml.j2 dest=/usr/local/share/sf-config-repo/jobs/_default_jobs.yaml

    - stat: path=/root/config
      register: config_done

    - name: Make a first admin connexion through SF SSO (force sf_users admin id:1)
      command: sfmanager sf_user list
      when: config_done.stat.exists != True

    - name: Create empty resources file
      shell: "echo 'resources: {}' > /tmp/empty_resources.yaml"
      when: config_done.stat.exists != True

    - name: Change default admin email in default resources file
      replace:
          dest: /usr/local/share/sf-config-repo/resources/resources.yaml
          regexp: '@sftests.com'
          replace: '@{{ fqdn }}'
      when: config_done.stat.exists != True

    - name: Create config repository resources
      command: /usr/local/bin/resources.sh direct_apply /tmp/empty_resources.yaml /usr/local/share/sf-config-repo/resources/resources.yaml
      when: config_done.stat.exists != True

    - command: mktemp -d
      register: conf_tmp
      when: config_done.stat.exists != True

    - name: Clone the config repository
      git: repo=git+ssh://gerrit/config
           dest={{ conf_tmp.stdout }}
      when: config_done.stat.exists != True

    - name: Sync /usr/local/share/sf-config-repo/ in the config repo
      command: rsync -av /usr/local/share/sf-config-repo/ {{ conf_tmp.stdout }}/
      when: config_done.stat.exists != True

    - name: Change default fqdn in default repoxplorer projects.yaml file
      replace:
          dest: "{{ conf_tmp.stdout }}/repoxplorer/projects.yaml"
          regexp: 'sftests.com'
          replace: '{{ fqdn }}'
      when: config_done.stat.exists != True

    - name: Push config repo
      command: git {{ item }} chdir={{ conf_tmp.stdout }}
      with_items:
        - "add -A"
        - "commit -m 'Initialize config repository'"
        - "push origin master"
      when: config_done.stat.exists != True

    - command: mv {{ conf_tmp.stdout }} /root/config
      when: config_done.stat.exists != True

- include: sf_configrepo_update.yml

- include: sf_postconf.yml
