role_actions:
  - install
  - setup

kibana_repo_name: kibana
kibana_repo_desc: Kibana repository
kibana_repo_url: https://packages.elastic.co/kibana/4.5/centos
kibana_repo_gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
kibana_repo_gpgcheck: 1

kibana_topmenu_patch: |
  function load_menu() { loadTopmenu(); }
  newScript = document.createElement('script');
  newScript.type = 'text/javascript';
  newScript.src = '/static/js/topmenu.js';
  newScript.onload = load_menu;
  document.getElementsByTagName('head')[0].appendChild(newScript);
