---
- include_vars: /etc/software-factory/sf_version.yaml

- name: Remove un-needed files
  file:
      path: "{{ item }}"
      state: absent
  with_items:
    - /etc/httpd/conf.d/autoindex.conf
    - /etc/httpd/conf.d/userdir.conf
    - /etc/httpd/conf.d/welcome.conf

- name: Create working directories
  file:
      path: "{{ item }}"
      state: directory
  with_items:
    - /var/www/sf

- name: Expose localCA.pem
  copy:
      content: "{{ localCA_pem }}"
      dest: /var/www/localCA.pem
      mode: "0444"

- name: Add embedded TLS certificate for apache
  when: not network['use_letsencrypt']
  notify: apache reload
  copy:
    content: "{{ item.content }}\n"
    dest: "/etc/pki/tls/{{ item.path }}"
    mode: "{{ item.mode|default(0444) }}"
    setype: "unconfined_u:object_r:cert_t:s0"
  with_items:
      - {content: "{{gateway_crt}}", path: "certs/{{ fqdn }}.crt"}
      - {content: "{{gateway_chain}}", path: "certs/{{ fqdn }}-chain.crt"}
      - {content: "{{gateway_key}}", path: "private/{{ fqdn }}.key", mode: '0400'}

- name: Install config files
  copy:
    src: "{{ item.name }}"
    dest: "{{ item.path }}/{{ item.name }}"
    mode: "{{ item.mode|default(0444) }}"
  with_items:
      - {name: base64helper, path: /usr/local/sbin, mode: '0755'}
      - {name: menu.js, path: /var/www/static/js}
      - {name: pages-404.html, path: /var/www/}
      - {name: ssl.conf, path: /etc/httpd/conf.d}
      - {name: user_settings.html, path: /var/www/sf}
      - {name: user_settings.js, path: /var/www/sf}
      - {name: welcome.html, path: /var/www/sf}
      - {name: welcome.js, path: /var/www/sf}

- name: Install index.html for zuul
  copy:
    src: zuul.index.html
    dest: /var/www/zuul/index.html
    mode: 0444

- name: Touch files
  file:
    path: "{{ item }}"
    state: touch
    mode: 0640
    owner: apache
    group: apache
  with_items:
      - /etc/httpd/managesf_htpasswd
      - /etc/httpd/pages.txt

- name: Install templates
  template:
      src: "{{ item.name }}.j2"
      dest: "{{item.dest }}/{{ item.name }}"
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.group | default('root') }}"
      mode: "{{ item.mode | default(0444) }}"
  with_items:
      - {name: gateway.common, dest: /etc/httpd/conf.d}
      - {name: gateway.conf, dest: /etc/httpd/conf.d}
      - {name: hideci.js, dest: /var/www/static/js}
      - {name: topmenu.html, dest: /var/www}
      - {name: topmenu.js, dest: /var/www/static/js}
  notify: apache reload

- name: Install Kibana SF gateway rules
  template:
      src: gateway-kibana.conf.j2
      dest: /etc/httpd/conf.d/gateway-kibana.conf
      mode: 0444
  with_items: "{{ inventory }}"
  when: '"kibana" in item["roles"]'
  notify: apache reload

- name: Load ssl module in apache configuration
  lineinfile:
      dest: /etc/httpd/conf.modules.d/00-ssl.conf
      line: "LoadModule ssl_module modules/mod_ssl.so"
      owner: apache
      group: apache
      mode: 0640
  notify: apache reload

- name: Add x-x509-ca-cert mime types
  lineinfile:
      dest: /etc/mime.types
      line: "application/x-x509-ca-cert                      der pem crt"
  notify: apache reload

- name: Load cache module in apache configuration
  lineinfile:
      dest: /etc/httpd/conf.modules.d/00-cache.conf
      line: "LoadModule cache_module modules/mod_cache.so"
      create: True
      state: present
      owner: apache
      group: apache
      mode: 0640
  notify: apache reload

- name: Install service file for socat_gerrit
  copy:
      src: socat_gerrit.service
      dest: /lib/systemd/system/socat_gerrit.service
      owner: root
      group: root
      mode: 0644
  register: install_service_file
  when: groups['gerrit'] != groups['gateway']

- name: Reload systemctl daemon
  shell: "systemctl daemon-reload"
  when:
      - install_service_file|changed
      - groups['gerrit'] != groups['gateway']

- name: Start socat_gerrit
  service:
      name: socat_gerrit
      enabled: yes
      state: started
  when: groups['gerrit'] != groups['gateway']

- name: Start service
  systemd:
      name: httpd
      state: started
      daemon_reload: yes
      enabled: yes
