# This file get appended to _layout.yaml
projects:
  - name: zuul-demo
    check:
      - zuul-demo-functional-tests
      - zuul-demo-unit-tests
    gate:
      - zuul-demo-functional-tests
      - zuul-demo-unit-tests
    periodic:
      - periodic-zuul-demo
