---
- name: "Install package"
  yum:
    name: "zuul-webui, zuul-server, zuul-merger"
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
