---
galaxy_info:
  description: Log indexation scheduler based on Gearman
  company: Red Hat
  license: Apache
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - software-factory
