---
- name: "Install package"
  yum:
    name: "gitweb, highlight, perl-Digest-MD5, gitweb-theme-kogakure"
    state: latest
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"

- name: "Copy theme to gitweb.css"
  file:
    src: "/var/www/git/static/{{ theme }}.css"
    dest: "/var/www/git/static/gitweb.css"
    remote_src: True
