---
- include: /etc/ansible/tasks/create_user.yml user_name=storyboard

- name: "Install storyboard.conf"
  template: src={{ item }}.j2 dest=/etc/storyboard/{{ item }} owner=storyboard group=storyboard mode=0400
  with_items:
    - storyboard.conf
    - superuser.yaml
    - service_token.sql
  notify: restart storyboard

- name: "Setup database"
  command: storyboard-db-manage upgrade head

- name: "Setup superusers"
  command: storyboard-db-manage load_superusers /etc/storyboard/superuser.yaml

- name: "Setup service_token"
  command: bash -c "mysql storyboard < /etc/storyboard/service_token.sql"

- name: Start service
  service:
      name: "{{ item }}"
      state: started
      enabled: yes
  with_items: "{{ storyboard_services }}"
