---
- file: path=/var/lib/software-factory/repoxplorer_config state=touch

- name: "Check local repoxplorer config"
  command: cat /var/lib/software-factory/repoxplorer_config
  register: localconfig

- name: "Check upstream repoxplorer config"
  command: chdir=/root/config git log --oneline repoxplorer/
  register: upstreamconfig

- name: "Update local repoxplorer configuration files"
  when: localconfig.stdout != upstreamconfig.stdout
  copy:
    src: /root/config/repoxplorer/{{ item }}
    dest: /etc/repoxplorer/{{ item }}
  with_items:
    - projects.yaml
    - idents.yaml

- name: "Write config repo sha1 matching current repoxplorer configuration"
  copy: content="{{ upstreamconfig.stdout }}" dest=/var/lib/software-factory/repoxplorer_config
  when: localconfig.stdout != upstreamconfig.stdout
