---
- name: "Install requirements"
  yum:
    name: "gzip,git,curl,python,openssl-devel,nodejs"
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"

- name: "Check version installed"
  command: cat /var/www/etherpad-lite/.norpmversion
  no_log: yes
  ignore_errors: yes
  register: etherpad_installed_version

- block:
    - name: "Remove previous installation"
      file: path=/var/www/etherpad-lite state=absent

    - name: "Extract release"
      unarchive:
        src: "{{ etherpad_source_url }}"
        remote_src: True
        dest: "/var/www/"

    - name: "Rename directory"
      command: mv "/var/www/etherpad-lite-{{ etherpad_version }}" /var/www/etherpad-lite

    - name: "Run installDeps"
      command: sh /var/www/etherpad-lite/bin/installDeps.sh

    - name: "Set the norpmversion file"
      copy:
        content: "{{ etherpad_version }}"
        dest: /var/www/etherpad-lite/.norpmversion

  when: etherpad_installed_version.stdout != "{{ etherpad_version }}"
