---
- include_vars: /etc/software-factory/sfcreds.yaml

- name: "Create group"
  group:
    name: "{{ group_name|default(user_name) }}"

- name: "Create user"
  user:
    name: "{{ user_name }}"
    group: "{{ group_name|default(user_name) }}"
    shell: "{{ shell|default('/sbin/nologin') }}"
    home: "{{ home_dir|default('/var/lib/' + user_name) }}"

- name: "Create home dir"
  file:
    path: "{{ home_dir|default('/var/lib/' + user_name) }}"
    state: directory
    mode: "{{ home_dir_mode|default('0750') }}"
    owner: "{{ user_name }}"
    group: "{{ group_name|default(user_name) }}"

- name: "Create user .ssh directory"
  when: ssh_key|default(None)
  file:
    path: "{{ home_dir|default('/var/lib/' + user_name) }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ user_name }}"
    group: "{{ group_name|default(user_name) }}"

- name: "Add ssh key"
  when: ssh_key|default(None)
  copy:
    content: "{{ hostvars[inventory_hostname][item.key] }}"
    dest: "{{ home_dir|default('/var/lib/' + user_name) }}/.ssh/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "{{ user_name }}"
    group: "{{ group_name|default(user_name) }}"
  with_items:
    - {key: "{{ ssh_key|default(omit) }}", name: "id_rsa", mode: "0400"}
    - {key: "{{ ssh_key|default(omit) }}_pub", name: "id_rsa.pub", mode: "0444"}
