---
- include: update_configrepo.yaml

- stat: path=/root/config/gerrit/replication.config
  register: rstat
- name: Check if replication.config changed
  command: diff /root/config/gerrit/replication.config /etc/gerrit/replication.config
  register: diffstat
  no_log: True
  when: rstat.stat.exists == True
  failed_when: diffstat.rc > 1
- name: Update Gerrit replication.config
  command: cp /root/config/gerrit/replication.config /etc/gerrit/
  when: rstat.stat.exists == True and diffstat.rc == 1
- name: Reload the replication plugin
  command: ssh -p 29418 admin@{{ fqdn }} gerrit plugin reload replication
  when: rstat.stat.exists == True and diffstat.rc == 1
- name: Restart the replication
  command: ssh -p 29418 admin@{{ fqdn }} replication start --all
  when: rstat.stat.exists == True and diffstat.rc == 1
