---
- stat: path=/root/config
  register: config

- git: repo=http://{{ fqdn }}/r/config dest=/root/config force=yes
  when: config.stat.isdir is not defined

- name: Reset config repo local copy
  when: config.stat.isdir is defined and config.stat.isdir
  command: chdir=/root/config {{ item }}
  with_items:
    # The git config replaces the http address in remote.origin.url.
    - git config -f .git/config --replace-all remote.origin.url http://{{ fqdn }}/r/config
    # The sed replaces the ssh address in remote.gerrit.url; however this might
    # not be set yet and therefore we can't use git config here, otherwise tests
    # are breaking
    - sed -i -e 's#url = ssh://admin@.*:29418/config#url = ssh://admin@{{ fqdn }}:29418/config#g' .git/config
    - git fetch --all
    - git reset --hard origin/master --
    - git clean -f -x -d
