---
- include_vars: /etc/software-factory/sfconfig.yaml

- name: Initalize version control for yaml files
  shell: git init .; git add *; git commit -m 'init'
  args:
      chdir: /etc/software-factory/
      creates: /etc/software-factory/.git

- name: Initialize git access
  template: src=sshconfig.j2 dest=/root/.ssh/config

- name: Initialize git config
  template: src=gitconfig.j2 dest=/root/.gitconfig

- name: Install backup trigger job
  copy:
    src: "{{ item.name }}"
    dest: "/usr/local/bin/{{ item.name }}"
    mode: 0500
  with_items:
      - {name: trigger_backup.sh}
      - {name: export_backup_swift.sh}

- name: Install auto_backup.conf
  template:
      src: auto_backup.conf.j2
      dest: /etc/auto_backup.conf
      mode: 0444

- name: Install crontab for backup nightly jobs
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    user: root
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
  with_items:
      - {name: backup_gerrit, job: /usr/local/bin/trigger_backup.sh, hour: "1", minute: "0"}
      - {name: auto_backup, job: /usr/local/bin/export_backup_swift.sh, hour: "5", minute: "0"}

- name: Start rsyncd
  service: name=rsyncd state=started enabled=yes
