---
galaxy_info:
  description: Gerrit service
  company: Red Hat
  license: Apache
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - software-factory
dependencies:
  - role: sf-handlers
  - role: sf-monit
