resources:
  projects:
    internal:
      description: Internal configuration project
      issue-tracker: SFStoryboard
      source-repositories:
        - config
  repos:
    config:
      description: Config repository (Do not delete it)
      acl: config-acl
  acls:
    config-acl:
      file: |
        [access "refs/*"]
          read = group config-core
          owner = group config-ptl
        [access "refs/heads/*"]
          label-Code-Review = -2..+2 group config-core
          label-Code-Review = -2..+2 group config-ptl
          label-Verified = -2..+2 group config-ptl
          label-Workflow = -1..+1 group config-core
          label-Workflow = -1..+1 group config-ptl
          label-Workflow = -1..+0 group Registered Users
          submit = group config-ptl
          read = group config-core
          read = group Registered Users
        [access "refs/meta/config"]
          read = group config-core
          read = group Registered Users
        [receive]
          requireChangeId = true
        [submit]
          mergeContent = false
          action = fast forward only
      groups:
        - config-ptl
        - config-core
  groups:
    config-ptl:
      description: Team lead for the config repo
      members:
        - admin@sftests.com
    config-core:
      description: Team core for the config repo
      members: []
