---
- name: "Add the elasticsearch RPM repository"
  yum_repository:
    name: "{{ elasticsearch_repo_name }}"
    description: "{{ elasticsearch_repo_desc }}"
    baseurl: "{{ elasticsearch_repo_url }}"
    gpgkey: "{{ elasticsearch_repo_gpgkey }}"
    gpgcheck: "{{ elasticsearch_repo_gpgcheck }}"

- name: "Install Elasticsearch package"
  yum:
    name: elasticsearch
    state: latest
    disablerepo: "*"
    enablerepo: "{{ elasticsearch_repo_name }}"
