- name: Create elasticsearch group
  group: name=elasticsearch
- name: Create elasticsearch user
  user: name=elasticsearch group=elasticsearch shell=/sbin/nologin home=/var/lib/elasticsearch
- name: Ensure /var/lib/elasticsearch directory exists
  file: path=/var/lib/elasticsearch state=directory mode=0700 owner=elasticsearch group=elasticsearch
- name: Ensure /var/run/elasticsearch directory exists
  file: path=/var/run/elasticsearch state=directory mode=0755 owner=elasticsearch group=elasticsearch
- name: Ensure Elasticsearch listen to all addresses
  lineinfile: dest=/etc/elasticsearch/elasticsearch.yml
              regexp="^network.host{{':'}} elasticsearch.{{ fqdn }}"
              insertafter="^# network.host:"
              line="network.host{{':'}} elasticsearch.{{ fqdn }}"
- name: Elasticsearch service started and enabled
  service: name=elasticsearch state=started enabled=yes
