---
- name: "Add the logstash RPM repository"
  yum_repository:
    name: "{{ logstash_repo_name }}"
    description: "{{ logstash_repo_desc }}"
    baseurl: "{{ logstash_repo_url }}"
    gpgkey: "{{ logstash_repo_gpgkey }}"
    gpgcheck: "{{ logstash_repo_gpgcheck }}"

- name: "Install logstash package"
  yum:
    name: logstash
    state: present
    disablerepo: "*"
    enablerepo: "{{ logstash_repo_name }}"
