- job-template:
    name: '{name}-upload-to-pypi'
    defaults: global
    builders:
      - prepare-workspace
      - shell: |
          cp $PYPIRC ~/.pypirc
          cd $ZUUL_PROJECT
          python setup.py register -r pypi
          python setup.py sdist upload -r pypi
    wrappers:
      - credentials-binding:
          - file:
              credential-id: '{pypirc}'
              variable: PYPIRC
    triggers:
      - zuul
    node: '{node}'
