---
- name: "Get database list"
  shell: mysql -ANe "SELECT schema_name FROM information_schema.schemata WHERE schema_name NOT IN ('mysql','information_schema','performance_schema')" | tr '\n' ' '
  register: dblist

- name: "Dump database locally"
  shell: mysqldump --databases {{dblist.stdout}} | gzip -9 > /root/mysqldump.sql.gz

- name: "Fetch dump"
  synchronize:
    mode: pull
    src: /root/mysqldump.sql.gz
    dest: "{{ backup_dest }}/mysqldump.sql.gz"
