# fqdn of the deployment used by authentication and in notification
fqdn: sftests.com

# Enable services debug mode
debug: False

# Default landing web page
welcome_page_path: "sf/welcome.html"

network:
    use_letsencrypt: false
    smtp_relay:
    # NTP main reference server
    ntp_main_server: pool.ntp.org

    # Set mail forward to your personal address to receive notification
    # Default to root mailbox on managesf node
    admin_mail_forward: root@localhost

    static_hostnames: []
    # Define static hostnames
    # - "8.8.8.8 google-dns.com"

authentication:
    admin_password: userpass
    # timeout of sessions in seconds
    sso_cookie_timeout: 43200

    # Enforce authentication for all services (such as etherpad and pastebin that doesn't require authentication by default)
    authenticated_only: false

    # Allowed URLs or URL prefixes that are accessible via the gateway This can
    # be used to ensure only authenticated users access the Jenkins logs on the
    # slaves. In this case the Jenkins slaves must be accessible only from the
    # gateway.
    # Can be either full domains or only prefixes, for example to allow
    # IP-ranges
    allowed_proxy_prefixes:
        - "198.154.188."
        - "127.0.0.1"
        - "sftests.com"

    ldap:
        disabled: True
        ldap_url: ldap://sftests.com
        ldap_account_base: ou=Users,dc=sftests,dc=com
        ldap_account_username_attribute: cn
        ldap_account_mail_attribute: mail
        ldap_account_surname_attribute: sn

    oauth2:
    # Currently supported OAuth2 providers are github, google, bitbucket
    # While it is technically possible to have as many of these providers used
    # at the same time, this might cause problems along the way with users
    # and/or email collisions between several providers.
    # Enable more than one at your own risk.
        github:
            disabled: False
            client_id:
            client_secret:
            # the github provider also lets you filter users logging in depending
            # on the organizations they belong to. Leave blank if not necessary
            github_allowed_organizations:
        google:
            disabled: False
            client_id:
            client_secret:
        bitbucket:
            disabled: True
            client_id:
            client_secret:

    openid:
    # Provider discovery is not supported by the OpenID auth plugin (see also
    # problems with multiple oauth providers as explained above). You must
    # therefore specify the openID server you wish to use.
    # Use the launchpad server by default
        disabled: False
        server: https://login.launchpad.net/+openid
        # what to display on the login button
        login_button_text: "Log in with Launchpad"

    openid_connect:
        disabled: True
        issuer_url:
        login_button_text: "Log in with OpenID Connect"
        client_id:
        client_secret:
        mapping:
            login: email
            email: email
            name: name
            uid: sub


gerrit_connections:
    - name: "external_gerrit"
      hostname: external-gerrit-hostname
      puburl: https://external-gerrit-host-name/r/
      username: external-gerrit-user-name
      disabled: True


theme:
    loginpage_custom_footer: ""
    # Right topmenu entry, next to the login/logout button
    topmenu_custom_entry: '<li><a href="/docs/" target="_top">Get started</a></li>'

backup:
    disabled: True
    os_auth_url:
    os_auth_version:
    os_tenant_name:
    os_username:
    os_password:
    swift_backup_container: sfbackups
    swift_backup_max_retention_secs: 864000

mirrors:
    # Set periodic update using time format, e.g. daily = '0 0 * * *'
    periodic_update: False
    swift_mirror_url: http://swift:8080/v1/AUTH_uuid/repomirror/
    swift_mirror_tempurl_key: container_tempurl_key
    swift_mirror_ttl: 15811200 # 6 months ttl

nodepool:
    disabled: True
    providers:
      - name: default
        auth_url: http://localhost:35357/v2.0
        project_id: tenantname
        username: username
        password: secret
        # Optional nodepool network uuid (required by heat based tenant when multiple network are available)
        network:
        # Compute availability zone
        pool: nova
        # Max amount of Slaves that can be started
        max_servers: 10
        # Delay in seconds between two tasks within nodepool
        rate: 10.0
        # Timeout in seconds for SSH login to node
        boot_timeout: 120

logs:
    disabled: True
    swift_logsexport_container: logs
    swift_logsexport_logserver_prefix: http://logs.sftests.com:8080/v1/AUTH_test/logs
    # Use Swift auth url for auth v1 and keystone auth url for auth v2
    swift_logsexport_authurl: http://logs.sftests.com:8080/auth/v1.0
    # Leave blank if auth v2 is used
    swift_logsexport_x_storage_url: http://logs.sftests.com:8080/v1/AUTH_test
    # For auth v1 use as username : username:tenantname
    swift_logsexport_username: username:tenantname
    swift_logsexport_password: password
    # Only used for auth v2
    swift_logsexport_tenantname: tenantname
    # Use 1 for using the tempauth of Swift or use 2
    # if you rely on a keystone authentication
    swift_logsexport_authversion: 1
    swift_logsexport_x_tempurl_key: tempurlkey
    # Do not create a new tempurl key, but use the above defined key instead.
    # Zuul will create a random key if not set, that might break other scripts
    # using a tempurl key
    swift_logsexport_send_tempurl_key: False

gerritbot:
    disabled: True
    ircserver: irc.freenode.net
    ircport: 6667
    botname: sfbot
    password: null

mumble:
    password: False
