# fqdn of the deployment used by authentication and in notification
fqdn: sftests.com

network:
    enforce_ssl: false
    smtp_relay:
    # NTP main reference server
    ntp_main_server: pool.ntp.org

    # Set mail forward to your personal address to receive notification
    # Default to root mailbox on managesf node
    admin_mail_forward: root@localhost

authentication:
    admin_password: userpass
    # timeout of sessions in seconds
    sso_cookie_timeout: 43200

    # Enforce authentication for all services (such as etherpad and pastebin that doesn't require authentication by default)
    authenticated_only: false

    # Allowed URLs or URL prefixes that are accessible via the gateway This can
    # be used to ensure only authenticated users access the Jenkins logs on the
    # slaves. In this case the Jenkins slaves must be accessible only from the
    # gateway.
    # Can be either full domains or only prefixes, for example to allow
    # IP-ranges
    allowed_proxy_prefixes:
        - "198.154.188."
        - "127.0.0.1"
        - "sftests.com"

    ldap:
        disabled: True
        ldap_url: ldap://sftests.com
        ldap_account_base: ou=Users,dc=sftests,dc=com
        ldap_account_username_attribute: cn
        ldap_account_mail_attribute: mail
        ldap_account_surname_attribute: sn

    oauth2:
    # Currently supported OAuth2 providers are github, google, bitbucket
    # While it is technically possible to have as many of these providers used
    # at the same time, this might cause problems along the way with users
    # and/or email collisions between several providers.
    # Enable more than one at your own risk.
        github:
            disabled: False
            client_id:
            client_secret:
            # the github provider also lets you filter users logging in depending
            # on the organizations they belong to. Leave blank if not necessary
            github_allowed_organizations:
        google:
            disabled: False
            client_id:
            client_secret:
        bitbucket:
            disabled: True
            client_id:
            client_secret:

    openid:
    # Provider discovery is not supported by the OpenID auth plugin (see also
    # problems with multiple oauth providers as explained above). You must
    # therefore specify the openID server you wish to use.
    # Use the launchpad server by default
        disabled: False
        server: https://login.launchpad.net/+openid
        # what to display on the login button
        login_button_text: "Log in with Launchpad"


gerrit_connections:
    - name: "external_gerrit"
      hostname: external-gerrit-hostname
      puburl: https://external-gerrit-host-name/r/
      username: external-gerrit-user-name
      disabled: True


theme:
    loginpage_custom_footer: ""
    # Logo (50px height): embeded base64
    topmenu_logo_style: "height: 50px; margin-top: -14px; margin-left: -14px; margin-right: -14px;"
    topmenu_logo_data: "iVBORw0KGgoAAAANSUhEUgAAADsAAAAyCAQAAABII2vwAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQffCgUUAgkCFz1DAAAGV0lEQVRYw7XXX4wkVRXH8c+trunpmZ6/O7vDjrDLwgoKGwkrFUjARB9IRGLwwWDEiAm8rBrwCYnBGIySgIliIglhJIEHYkyM0cSEGB94wIhE7VUkEiCCMPtnht3Z+T89/7qry4funp3/08sup1+qq+reb/3OPfeec4KLsJIEpfqfADKs3k22HRk+PJJEiaDoakdcq8+cN73pHWVZsvpZlxDb0Bns9V0PKmx4/JinnUlq24PDRUAjj3t425eO+VVS3g4cPjR0yFO+vO1LmeBF305ObA0OrSC2uH/YU74g22X8K76anLpAJzeRpYJOkaihIjWjzy98bVdofZUfTxY2f3zYxZUdDrrHvfbrbDx4zxP6PdHymlyfvNmy2gb0oAc95OLsSY8m8y1hG9DDnnF7a3MHZalOcf28WG8HNq9vtNUkCUp7POL287PstIyRRe/6t1mhxa0RbX3+lCK3ub8eNEFQs7SFjsyCWStS4yryJsyrKJuV7uLReJvPGfT9+oBMVZtpI67Wp7JmQLBoxIRBNXPaFExakjNvyaf07ag23trFBt0iE4Ilp/WZE5lQsWSfwqruTKRgRrs9esRmLFoQNp6VWYtqS8G+utYgM2FBn8stOCmnR2fDhZkeXaZ0OazDoswBsRHj2nUKTdp/zPNXBZ/e1cmheb9mSZ8hy2b06TIpr9IIiKCios1BHf5nSk2XA660qKKi0JT5D9d59Vb8Td7RHSO5ZrZ+NetdQeSMy81a0OYts3LIlJ02Zb9+J0wbMGTZSSs6LRo1oVqf4j6/Lt1XuoVbHG3m5vXY0vnLEfP1kzAvyLRJ5RHJqTa2zHtOWtFmxbx+h1zjMnOWdSuY8oa55lxXes7vS/eVBhoZ+jz2NX9v7tee0jWlWyVeItjraiuqisZEChZda78UQUF7w9mRqmVLqnKoqcnplluraMhzHisdJHG8ubYlN4Lj12W3+oQjrtdhsh42OQvG7FeUOqOmJhVkii5XdE7ZoH6nnZI3rkfRhBX77FPcGM/ftOf4t6LJo3XsaqZ5IPvSmsPwsuYW6Zc3albRHtREVmTadOpVM6rHXkxa0u+QijkdDsivPzLqh8ZXspGjD1MSVqE/9OjWQZ0TTDltv0ErqjJjcobU5Jx0Wq9Be9WkCmaMKOt21ZrdvcFuVkqyxkYp/cgPtisTqig6LG/FrLPyajgl6LAkMqNsThGpMcti5ww21n0Le9RdsgClO724W9IOMjkTTugVY1Fqr3nzitpMKSPWr928zBW6tptoQU+SxiUKfrZ7eZMJysZ16zMlp0eqrMdendrFKpYNOCBvXtheq3q5EOHjPtlaVq1aQCpCVWZWu15BRb9eRQNiqaKOHTWEttfEONIaNNNlyAza5VQtOaBTFZmCj6k26p5aC3PFTdmtJec2cygI5lQNiBqQmg5BbbvoXWuVrHKjGB+0is10OiT1gZwh5GWiVVwkkyFW20nxG021r7eOLShKFUR6kQomVO3RZsG0Ph0Y0bfxhFprD6kRJYz5Q+vgqkyvblWpIDJnzJJY2agVsdQ5C8JqYb3BXk5eSrKSCLUdOpktre7EcW+ZFqmaM21RilOmRSJn/NeZza4+6TulQCIqSSRvu/9Cy9/MvHFlXQ7irE5XyJvSZkCfWefMrsVmeN+9yetJVkIU11Pe877RUuRvKEHOmrRoypRJVactGlNxSlm0fu8GL7gnebmZeMKaDPRZd/he62pP+kC0GslBTopMLEXNgIPN2uhVz/pTMnqeFeC4m+rgXje4xhEDuhUUFMSNFJRbHyEhS6ORofE9OWZNbIieTMFgFvWMHvpz+9nsrH96xztJtrZ/DJv6u1i3vFgkkmuU+ZuK/VxWjt9+pPp1P/WkwoanmbLn3Rn98bKHrhpdriTlzU1rvK4BkUiqplpb2mdmAje7w8T6+kWm5hC1xffP3DUNf9HjhnXNZrypMG/RftmWRbjNTc0ScZ11I7Q3PuczLTcjLYQUWPIvY5vUtvvc9gn3orAN+8mxHw/nNq7tsXT4N+7eKftdLPaB4bs3lwjDqau27n0uFXbQ4IcZdrHYFzy7RS895Wm3XWBbfUHWrauxr9f+2uU/WrVf9Pkt2/zCR4UNIsQ7zBB/BNhjy8MvOSzdNl67/dzEJcYOO8Zv/W6XaiBzaW3YcIvvbW3/B/8dNPPjOEXDAAAAAElFTkSuQmCC"
    # Favicon: embeded base64
    favicon_data: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAUwwAAFMMBFXBNQgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAkmSURBVGiB1Zp7bF5lHcc/z3PO27ft+663bW13YxdGBsThlsLC2JRtFQQUYzBEDYmiEoRFjOggQdQ5o4ngFNHgJSMQEwPByURCmJfdGHRt2d6tAttk68ZGN0pLu27tez/nPD//OL2c3t62bzuI36Q5Oc/ze37P7/f8rud5q0SEjwJ1dW9PKyyMp2tqapzJ8FEflgINDU0LRNTXleIWkEVAOSBAB9CklHrWtt1tNTU1FybC96Ir0Nj4VpWI9wTIbYAag/wCyI9aWpqfuP32273x8L+oCjQ0vHErmKeB6RNZpxT1qRS3rFmz7PyYtBdLgYaGplXALqAgPw4qFgq5tWO5lJ0fc6ivP7hYa/1pEWaKUKaUnBTRDaWloaZEwlQB28hbeACpcRzrQeDhXFQTtsDrr7+xzhizCVg9dC4cLqCioiwbiRQ5hYXhSEFBCGMMIkImk6W7O05PT4J4PMk49+1Op5mfy5XGbYGtW7da8+Zdtgl4CNDBuYqKUqqrZ1JSEgX/1IedfFFRIWVlJQBkMllaWz+gvb0TY0yubUvCYfk28JPRCMZtgcbGpkdFeCA4Fg4XsHDh3H7BAIwREokkyWSKbNZBa43WmqKiMNFoBNu2+mld1+XEiRa6unK6ed211y4bZu0+jMsCjY3/uVGEDcGxiopSFi+ej9a+MRKJFO3tnXR2duG6o2fAkpIos2dXUlZWgm3bLFmykPff7+D06bOjuVU2l2zjdCF5mEAOr6qazoIFc1FK4boeLS3v0dbWOS5O3d1xurvjRCJFLF48n6KiQqqrZ1BQEOL48VMjKKEyufjpXJPg+74INX3v5eWlLFw4D6UUmUyWw4ePjVv4IBKJFG++eYyOji7At+jChXNHoDTJXHzGVGD27EVzgAhAQUGISy+dB0A6neGNt46TTOU8oJwwxtDcfJrOTj/JVFZOZ8aM8kE0Sqm3c/EYU4Hu7tI2/J6FRYsuwbZtjDEcO3aKTa+m+MFrDv89lzOTjIkTJ04TjycAmD9/NpY1EOgi6msNDU13bd/eHM5LgZtvXpwB1RaNFlNWNg2AlpZWkskUjvH9NeVOSn6MEU6ebEFECIVCzJ1bHZiVamBLeXn8dH39oW9MVAFVVxe7RCk5NmtWJQCO49DW1gGA13vwk1UAIJlM097ux9LMmRX92S2AKqXUkw0NTU/v2bOnsG9wWBZqbDx4lYi+D/g4cIVlWVGtLSoqSgFobf0AYwTP9PoVkJ4CBQDa2zupqpqBbVuUl5f0x8YQ3BkOlyWAb0HAArFYLNTQ0LRFRDcBdwHXAFGAaLQYpfwseu6cX3TcQLpLuVPTECYSKZLJNMCg4jgUSrG+t1n0FThy5EiB49gv9go+rGePRot9oV2XdNrPOq4ZIJsKF+pDT08cgOLiolxkCtST27c3h21/UfbHwE2jUUcivgLx+EBKds3AqWe8qWvJk8kUAEVFIyadAOTysrL45/S+fbFLRXgwF2mf+wQbL1dGt4AA+983tCUHK3Y2LhxqH5xyu7Ow692BMcfx2xCtNZY1ZpKco7W2vghYuaj6ynufIgBu4NSDQXwuDU+95fFCs0emtyVyDfzjlOH3TS7tgboaazM8HnM4GqgjwexjTG7LKiXVNqilA/kktwJB5sG4Tbl+Vtp71mNPi8ENHPKpbmHbcY/OlL9AELrSwgvNHs3n/TEjcNllC3Acp38vERnHN4OqtMF0jPWtncn4gRuJDARWUMi4A7855NKRGrzhjlMeJy/IoOM5dk5obHXJBhpWAVzXo7p65gB/1yMSKSKRSI0ql4g6qEX4IKf0wIULfmawbZviYr+GBC3gGoYJD3BiiPAAbUkZJDz4rpJKpQeNhUI2S5cuYenSJYNai6D8xphtGtQOIGcz09OT6DdnX37O0fJPGIIapgCA53mcOnUGzxu+mVL8ddWq5e/plSuX7RPht7k2MMbQ1dUNwKxZlViWHlTIpgJDFXAcl8OHm+npSYxE/q7jWN+E3kJWUOB9Hziea4MzZ1oB37TV1TMHxcBUIJt18HqbK/8743h/TQhChFat5QurVy/tgt5eqKamJhmLxa53HGsrsGqkDZLJNJ2dXUSjEdLpDJXFinWXjJmnx4VIyE8iqVQay9IcPXqCbHb4lalS8k9jrK+sWHFVe/9YMFXFYrGQ4+h7Qd8LcvlQBrZt43neeK9EJozq6pl0dHThuoMqYwbU30TMkytXLt/FkJw/6q3Evn2H5tu2DosYWylCQEhEbKXsEBDyPAlZltie58+B2P6TkFKERLStlNGAA8oBHBHJaj3w7o/1PZUjItlQSPWO+c9Uyj6/Zs2V8dGU/tBupy8WpsaJP0LkfTcKcMMjsVLPMuuVUssRmY5wUhT/3r3hmq0S8FUFat3m1zfm4iVwbNeGFc9MVIa8XWjtL/Yv04qdQMUI03vD4fIbX75vcQZg0yb03sj+MUqfvLxzw4rPTFSOvC2glWwFVSHIaxr1R9GcFEOthnsFPpnJdP0cuH/YQsUPETUsKAX1Tj5y5GWB2sfq5+DZZ4Aslrto5/0rz/bNfWrzgS8J8ixwziQSVbs3rnGDFnAcu3LvQ8vH7L/Gi7yC2EkX9t1XhrQXuiI4t3PD1c+JkpuUcMc0pk3i94HxIe8YqN28/3ngtt7XOoG/KGX/fef3lp8eShu0gDJmnad0V3DecqVlx0MrJn4/ySRiwBRHvqoTiXdQ3AOsUrAKcR+v3bz/iBL5kxeJ/m73+uEFSLTeNdTsElJ3A1vykSPvOrB7/ZXxnQ9cs8EkEjOUyK3AFoQ24EpR6hGdTNSvfrRu2ghL9wGvBP+USGu+cuRlgdrH6ucYUzDNdVJtr25c0wW8BLy0aRP3vDLtwGeVkaeAj4Wt0B3AH4JrHcf+/EcexOLZP9Nijobt8E+D4xs3YnZ99+oXlfA8gBg1ayqEzIW8FNCwA0Dgztpf7b8uOLf20ca5oviy/6b+NVkBx0JeLnS+RD9X2i3fAanB8GrtLw+8guFtlFyltV7Ry/fg9cmr66dW3OHIywIH7q5xQpZzI/BnwENkLUruAa7r5flMJKE/sXFj7m/tqcCk2+m1v24qs7KZ5ShdCfKeF4keGil93rD5wBqArhJVd+Duyf2HShD/998D/wOjsUTRYfRCLQAAAABJRU5ErkJggg=="


    # By default all service entries in the topmenu are shown. However, it might be
    # required to disable individual entries. Note that this only disables the menu
    # entry, not the service itself.
    topmenu_hide_redmine: false
    topmenu_hide_etherpad: false
    topmenu_hide_paste: false

    # Right topmenu entry, next to the login/logout button
    topmenu_custom_entry: '<li><a href="/docs/" target="_top">Get started</a></li>'

backup:
    disabled: True
    os_auth_url:
    os_auth_version:
    os_tenant_name:
    os_username:
    os_password:
    swift_backup_container: sfbackups
    swift_backup_max_retention_secs: 864000

mirrors:
    # Set periodic update using time format, e.g. daily = '0 0 * * *'
    periodic_update: False
    swift_mirror_url: http://swift:8080/v1/AUTH_uuid/repomirror/
    swift_mirror_tempurl_key: container_tempurl_key
    swift_mirror_ttl: 15811200 # 6 months ttl

nodepool:
    disabled: True
    providers:
      - name: default
        auth-url: http://localhost:35357/v2.0
        project-id: tenantname
        username: username
        password: secret
        # Optional nodepool network uuid (required by heat based tenant when multiple network are available)
        network:
        # Compute availability zone
        pool: nova
        # Max amount of Slaves that can be started
        max-servers: 10
        # Delay in seconds between two tasks within nodepool
        rate: 10.0
        # Timeout in seconds for SSH login to node
        boot-timeout: 120

logs:
    disabled: True
    swift_logsexport_container: logs
    swift_logsexport_logserver_prefix: http://logs.sftests.com:8080/v1/AUTH_test/logs
    # Use Swift auth url for auth v1 and keystone auth url for auth v2
    swift_logsexport_authurl: http://logs.sftests.com:8080/auth/v1.0
    # Leave blank if auth v2 is used
    swift_logsexport_x_storage_url: http://logs.sftests.com:8080/v1/AUTH_test
    # For auth v1 use as username : username:tenantname
    swift_logsexport_username: username:tenantname
    swift_logsexport_password: password
    # Only used for auth v2
    swift_logsexport_tenantname: tenantname
    # Use 1 for using the tempauth of Swift or use 2
    # if you rely on a keystone authentication
    swift_logsexport_authversion: 1
    swift_logsexport_x_tempurl_key: tempurlkey
    # Do not create a new tempurl key, but use the above defined key instead.
    # Zuul will create a random key if not set, that might break other scripts
    # using a tempurl key
    swift_logsexport_send_tempurl_key: False

gerritbot:
    disabled: True
    ircserver: irc.freenode.net
    ircport: 6667
    botname: sfbot
    password: null

mumble:
    disabled: False
    password: False
    super_user_password: CHANGEME
