---
galaxy_info:
  description: Common services of software factory instances such as postfix
  company: Red Hat
  license: Apache
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - software-factory
