role_actions:
  - setup

etherpad_mysql_host: "mysql.example.com"
etherpad_mysql_port: 3306
etherpad_mysql_db: "etherpad"
etherpad_mysql_user: "etherpad"
etherpad_mysql_password: "CHANGE_ME"

etherpad_admin_key: "CHANGE_ME"
