---
- include_vars: /etc/puppet/hiera/sf/sfconfig.yaml

- name: "monit: ensure directories exist"
  file: 
    owner: root
    group: root
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
      - "/etc/monit"
      - "/etc/monit.d"

- name: "monit: manage monitrc"
  template:
    src: monitrc.j2 
    dest: /etc/monitrc
    owner: root
    group: root
    mode: 0600
  notify:
    - restart monit

- name: "monit: add system checks"
  copy:
    src: "{{ item }}"
    dest: "/etc/monit.d/{{ item }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - rootfs
    - system
  notify:
    - restart monit

- name: "monit: start service"
  service: name=monit enabled=yes state=started

