---
- name: Check if policy config is already in config-repo
  stat: path=/root/config/policies
  register: configrepo_policies

- name: Check if policy config has agent api entries
  when: configrepo_policies.stat.exists == true
  shell: grep -q managesf.node:get /root/config/policies/policy.yaml
  register: grep
  ignore_errors: yes

- name: Init policy configuration
  when: configrepo_policies.stat.exists == true and grep.rc == 1
  command: chdir=/root/config {{ item }}
  with_items:
    - git fetch --all
    - git reset --hard origin/master --
    - git clean -f -x -d
    # Create default rules
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.node:get rule:any
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.node:hold rule:admin_or_service
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.node:delete rule:admin_or_service
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.node:image-get rule:any
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.node:image-update rule:admin_or_service
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.node:add_authorized_key rule:admin_or_service
    - git add policies
    - git commit -m "Initialize job API policies"
    - git push git+ssh://{{ fqdn }}/config master
