---
- name: Check old install path
  stat: path=/usr/share/redmine
  register: usr_share_redmine

- name: Move files from /usr/share/redmine to /var/www/redmine
  when: usr_share_redmine.stat.isdir is defined and usr_share_redmine.stat.isdir == True
  command: "{{ item }}"
  with_items:
      - mkdir -p /var/www/redmine/log /var/www/redmine/public/plugin_assets
      - rsync -av /usr/share/redmine/log/ /var/www/redmine/log/
      - rsync -av /usr/share/redmine/public/plugin_assets/ /var/www/redmine/public/plugin_assets/
