---
- name: Check if policy config is already in config-repo
  stat: path=/root/config/policies
  register: configrepo_policies

- name: Init policy configuration
  when: configrepo_policies.stat.exists == false
  command: chdir=/root/config {{ item }}
  with_items:
    - git fetch --all
    - git reset --hard origin/master --
    - git clean -f -x -d
    - mkdir policies
    # Copy default policy.json
    - cp {{install_path}}/softwarefactory/usr/local/share/sf-config-repo/policies/policy.yaml policies/
    - git add policies
    - git commit -m "Initialize policy configuration"
    - git push git+ssh://{{ fqdn }}/config master
