---
- name: Stop Gerrit service
  service: name=gerrit state=stopped

- name: Fix replication known_hosts
  command: "{{ item }}"
  with_items:
    # Aggregate known_hosts and || true in case gerrit default known_hosts is not present
    - bash -c "cat /home/gerrit/.ssh/known_hosts /home/gerrit/.ssh/known_hosts_gerrit > /home/gerrit/.ssh/kh || true"
    - mv /home/gerrit/.ssh/kh /home/gerrit/.ssh/known_hosts_gerrit
    - rm -f /home/gerrit/.ssh/known_hosts
    - ln -s /home/gerrit/.ssh/known_hosts_gerrit /home/gerrit/.ssh/known_hosts
    # Fix default replication of config repo
    - sed -i /home/gerrit/site_path/etc/replication.config -e 's#/home/gerrit/site_path/git/#/home/gerrit/git/#'

- name: Upgrade Gerrit schema
  shell: /usr/bin/java -jar /home/gerrit/gerrit.war init -d /home/gerrit/site_path --batch --no-auto-start

- name: Ensure old reviewers by blame plugin has been removed
  file: path=/home/gerrit/site_path/plugins/reviewersbyblame-2.8.1.jar state=absent

- name: Create secondary Gerrit index
  shell: /usr/bin/java -jar /home/gerrit/gerrit.war reindex -d /home/gerrit/site_path

- name: Fix Gerrit permissions
  file: path=/home/gerrit/ state=directory recurse=yes owner=gerrit group=gerrit

- name: Start Gerrit service
  service: name=gerrit state=started

- name: Stop Apache service
  service: name=httpd state=stopped
  when: "'redmine' in roles"

- name: Migrate Redmine DB
  shell: /usr/bin/bundle exec rake db:migrate --trace RAILS_ENV=production chdir=/var/www/redmine
  when: "'redmine' in roles"

- name: Migrate Redmine plugins
  shell: /usr/bin/bundle exec rake redmine:plugins --trace RAILS_ENV=production chdir=/var/www/redmine
  when: "'redmine' in roles"

- name: Clear Redmine cache and sessions
  shell: /usr/bin/bundle exec rake tmp:cache:clear tmp:sessions:clear --trace RAILS_ENV=production chdir=/var/www/redmine
  when: "'redmine' in roles"

- name: Start Apache service
  service: name=httpd state=started
  when: "'redmine' in roles"
