---
- name: "Add the kibana RPM repository"
  yum_repository:
    name: "{{ kibana_repo_name }}"
    description: "{{ kibana_repo_desc }}"
    baseurl: "{{ kibana_repo_url }}"
    gpgkey: "{{ kibana_repo_gpgkey }}"
    gpgcheck: "{{ kibana_repo_gpgcheck }}"

- name: "Install kibana package"
  yum:
    name: kibana
    state: latest
    disablerepo: "*"
    enablerepo: "{{ kibana_repo_name }}"
